Upgrade to net7
Flexberry/FlexberryGisTestStand.ODataBackend pull request #17
Opened 2023-04-28 11:52 UTC by neroslovegor

2023-04-28 12:23 UTC, bratchikov requested changes

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/FlexberryGisTestStand.ODataBackend.csproj
>      <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
Используем Flexberry.ruleset. Посмотри в репо ORM - возьми файл оттуда.

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/FlexberryGisTestStand.ODataBackend.csproj
> +    <OutputType>Exe</OutputType>
Странная настройка. Точно exe?

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +                    Assembly.Load("NewPlatform.Flexberry.GIS.Objects"),
Если ссылка на сборку стоит, то лучше сделать не через строку, а как ниже - берём тип и сборку у него.

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +                // Map OData Service
В конце комментариев надо ставить точку - по правилам написания предложений. Проверь весь этот файл, несколько проблем есть таких.

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +        private static void CallbackAfterCreate(DataObject dataObject)
Если он пустой, то не нужен.

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/controls/FileUploaderHandler.ashx.cs
> -﻿using System;
А этот хэндлер для загрузки файлов как-то переписан в новой версии?

2023-04-28 12:23 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/Objects/Address.cs
> +        public virtual Microsoft.Spatial.Geometry Location
Тип поправлен в UML?

2023-05-02 10:06 UTC, neroslovegor commented on Docker/gis-test-stand-odata/sources/ODataBackend/controls/FileUploaderHandler.ashx.cs
> -﻿using System;
Вынесено в отдельную задачу.

2023-05-02 10:31 UTC, bratchikov requested changes

2023-05-02 10:31 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/FlexberryGisTestStand.ODataBackend.csproj
>      <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
Повторяющаяся настройка.

2023-05-02 10:31 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/Objects/FlexberryGisTestStand.Objects.csproj
>      <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
Flexberry.ruleset же надо подключить ко всем проектам этого солюшена. См. настройки проекта в студии.

2023-05-02 11:14 UTC, bratchikov approved these changes

2023-05-02 12:45 UTC, merged