Fix backgroudLayers.xml build and path
Flexberry/FlexberryGisTestStand.ODataBackend pull request #25
Opened 2023-05-22 10:10 UTC by DubrovinPavel

2023-05-23 09:49 UTC, TeterinaSvetlana commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +                xml.Load(Path.Combine(Directory.GetCurrentDirectory(), "shared/backgroundLayers.xml"));
а локально проверял что отображаются картинки этих слоев?

2023-05-23 10:00 UTC, bratchikov requested changes

2023-05-23 10:00 UTC, bratchikov commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +                xml.Load(Path.Combine(Directory.GetCurrentDirectory(), "shared/backgroundLayers.xml"));
Сложи 3 пути через Path.Combine (чтобы не привязываться к слешам) и проверь, что файл существует, иначе выдай внятную ошибку.

2023-05-29 04:34 UTC, DubrovinPavel commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +                xml.Load(Path.Combine(Directory.GetCurrentDirectory(), "shared/backgroundLayers.xml"));
прямо отображение не смотрел, но по пути xml нашлось

2023-05-29 05:15 UTC, TeterinaSvetlana commented on Docker/gis-test-stand-odata/sources/ODataBackend/Startup.cs
> +                xml.Load(Path.Combine(Directory.GetCurrentDirectory(), "shared/backgroundLayers.xml"));
у меня не отображалось)) там Игорь предложил с Path.Combine, с ним должно быть ок

2023-05-29 10:07 UTC, pepelyaeva approved these changes

2023-05-30 04:32 UTC, bratchikov approved these changes

2023-05-30 05:12 UTC, merged